name: github fmt

on: [dev, main]

jobs:
  fmt:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno: ['v1.x']

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2.3.0
        with:
          deno-version: ${{ matrix.deno }}
      
      - name: Run Formatting
        run: deno fmt src
